<?php
	class history_approval_m extends CI_Model
	{
		
		//private $tabel = 'MSU.TM_MASTER_LiST_OBSOLETE';

	    function get_history_register() {
	        $query = $this->db->query("SELECT DE.CHR_DEPT, D.CHR_NO_DOC, D.CHR_DOCUMENT_NAME, D.CHR_DOCUMENT_DESC, C.CHR_CATEGORY_NAME, D.INT_REVISION, R.CHR_APPROVED_MSU_BY, R.CHR_APPROVED_MSU_DATE, R.CHR_APPROVED_MANAGER_DATE, R.CHR_APPROVED_GM_DATE  FROM MSU.TT_REGISTER_DOC R JOIN MSU.TM_DOCUMENT D ON R.INT_ID_DOC = D.INT_ID_DOCUMENT JOIN MSU.TM_CATEGORY_DOC C ON D.INT_ID_CATEGORY = C.INT_ID_CATEGORY JOIN TM_DEPT DE ON R.INT_ID_DEPT = DE.INT_ID_DEPT WHERE R.INT_APPROVED_MSU = 1 ORDER BY R.INT_ID_REGISTER DESC");
	        return $query->result();
	    }

	    function get_history_revision() {
	        $query = $this->db->query("SELECT DE.CHR_DEPT, D.CHR_NO_DOC, D.CHR_DOCUMENT_NAME, D.CHR_DOCUMENT_DESC, C.CHR_CATEGORY_NAME, D.INT_REVISION, R.CHR_APPROVED_MSU_BY, R.CHR_APPROVED_MSU_DATE, R.CHR_APPROVED_MANAGER_DATE, R.CHR_APPROVED_GM_DATE  FROM MSU.TT_REVISION_DOC R JOIN MSU.TM_DOCUMENT D ON R.INT_ID_DOCUMENT = D.INT_ID_DOCUMENT JOIN MSU.TM_CATEGORY_DOC C ON D.INT_ID_CATEGORY = C.INT_ID_CATEGORY JOIN TM_DEPT DE ON R.INT_ID_DEPT = DE.INT_ID_DEPT WHERE R.INT_APPROVED_MSU = 1 ORDER BY R.INT_ID_REVISION DESC");
	        return $query->result();
	    }

	    function get_history_obsolete() {
	        $query = $this->db->query("SELECT DE.CHR_DEPT, D.CHR_NO_DOC, D.CHR_DOCUMENT_NAME, D.CHR_DOCUMENT_DESC, C.CHR_CATEGORY_NAME, D.INT_REVISION, R.CHR_APPROVED_MSU_BY, R.CHR_APPROVED_MSU_DATE, R.CHR_APPROVED_MANAGER_DATE FROM MSU.TT_OBSOLETE_DOC R JOIN MSU.TM_DOCUMENT D ON R.INT_ID_DOCUMENT = D.INT_ID_DOCUMENT JOIN MSU.TM_CATEGORY_DOC C ON D.INT_ID_CATEGORY = C.INT_ID_CATEGORY JOIN TM_DEPT DE ON R.INT_ID_DEPT = DE.INT_ID_DEPT WHERE R.INT_APPROVED_MSU = 1 ORDER BY R.INT_ID_OBSOLETE DESC");
	        return $query->result();
	    }
	}
?>