<?php
	class history_copy_m extends CI_Model
	{
		
		//private $tabel = 'MSU.TM_MASTER_LiST_OBSOLETE';

	    function get_history_copy() {
	        $query = $this->db->query("SELECT DE.CHR_DEPT, D.CHR_NO_DOC, D.CHR_DOCUMENT_NAME, D.CHR_DOCUMENT_DESC, C.CHR_CATEGORY_NAME, D.INT_REVISION, R.INT_TOTAL, R.CHR_APPROVED_MSU_BY, R.CHR_APPROVED_MSU_DATE, R.CHR_CREATED_BY  FROM MSU.TT_COPY_DOC R JOIN MSU.TM_DOCUMENT D ON R.INT_ID_DOCUMENT = D.INT_ID_DOCUMENT JOIN MSU.TM_CATEGORY_DOC C ON D.INT_ID_CATEGORY = C.INT_ID_CATEGORY JOIN TM_DEPT DE ON R.INT_ID_DEPT = DE.INT_ID_DEPT WHERE R.INT_APPROVED_MSU = 1 ORDER BY R.INT_ID_COPY DESC");
	        return $query->result();
	    }

	}
?>